apiVersion: v1
kind: Secret
metadata:
  name: devpulse-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devpulse.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  POSTGRES_URL: {{ .Values.secrets.postgresUrl | b64enc }}
  MONGO_URI: {{ .Values.secrets.mongoUri | b64enc }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc }}
