apiVersion: v1
kind: Service
metadata:
  name: url-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devpulse.labels" . | nindent 4 }}
    app: url-service
spec:
  type: ClusterIP
  selector:
    app: url-service
  ports:
    - port: {{ .Values.urlService.port }}
      targetPort: {{ .Values.urlService.port }}
      protocol: TCP
